### ISSUE TITLE
Slow response to back arrow 

### ISSUE THREAD

**Issue by ishansgoel** [hyperfan-dev/hyperfan-issues-repo#8]
<img width="481" alt="Screen Shot 2022-02-26 at 6 19 19 PM" src="https://user-images.githubusercontent.com/93004539/155864293-0ca8428e-f06f-44b4-88a9-f2dc654ec39f.png">

**Comment by anuccio15** [comment]
turns out this wasn't responding "slow" but actually the button was so small it was hard to click. made it bigger and it is working now. will be in testflight version 1.2 build 7
